app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'dashboard', 'uses' => 'Controller@index']);
Route::post('/login', ['as' => 'user.auth', 'uses' => 'Controller@auth']);
Route::get('/login', ['as' => 'user.login', 'uses' => 'Controller@login']);

Route::get('share/{username?}', ['as' => 'user.share', 'uses' => 'Controller@share']);

Route::middleware(['auth'])->group(function () {
    Route::resources([
        'tag' => 'TagsController',
        'tag-category' => 'TagCategoriesController',
        'course' => 'CoursesController',
        'webinar' => 'WebinarsController',
        'audio' => 'AudioController',
        'material-category' => 'MaterialCategoriesController',
        'material' => 'MaterialsController',
        'notification' => 'NotificationsController',
        'device' => 'DevicesController',
        'program' => 'PartnerProgramsController',
        'user' => 'UsersController',
        'meeting' => 'MeetingsController',
        'qualification' => 'QualificationsController',
        'package' => 'PackageNotificationsController',
    ]);

    Route::get('/logout', ['as' => 'user.logout', 'uses' => 'Controller@logout']);

    Route::post('/tag-remove', ['as' => 'tag.remove', 'uses' => 'TagsController@remove']);

    Route::post('/tag-category-remove', ['as' => 'tag-category.remove', 'uses' => 'TagCategoriesController@remove']);

    Route::post('/course-remove', ['as' => 'course.remove', 'uses' => 'CoursesController@remove']);
    Route::post('/course-sequence', ['as' => 'course.sequence', 'uses' => 'CoursesController@sequence']);
    Route::resource('course.video', 'VideosController', ['except' => ['index']]);
    Route::get('course/{course_id}/video', ['as' => 'course.video.index', 'uses' => 'VideosController@list']);
    Route::post('/course-video-remove', ['as' => 'course.video.remove', 'uses' => 'VideosController@remove']);
    Route::post('/course-video-sequence', ['as' => 'course.video.sequence', 'uses' => 'VideosController@sequence']);
    Route::post('/course-video-details', ['as' => 'course.video.details', 'uses' => 'VideosController@details']);

    Route::post('/webinar-remove', ['as' => 'webinar.remove', 'uses' => 'WebinarsController@remove']);

    Route::post('/audio-remove', ['as' => 'audio.remove', 'uses' => 'AudioController@remove']);
    Route::post('/audio-sequence', ['as' => 'audio.sequence', 'uses' => 'AudioController@sequence']);
    Route::post('/audio-details', ['as' => 'audio.details', 'uses' => 'AudioController@details']);

    Route::post('/material-category-remove', ['as' => 'material-category.remove', 'uses' => 'MaterialCategoriesController@remove']);
    Route::post('/material-remove', ['as' => 'material.remove', 'uses' => 'MaterialsController@remove']);
    Route::post('/material-sequence', ['as' => 'material.sequence', 'uses' => 'MaterialsController@sequence']);

    Route::post('/notification-remove', ['as' => 'notification.remove', 'uses' => 'NotificationsController@remove']);

    Route::post('/device-remove', ['as' => 'device.remove', 'uses' => 'DevicesController@remove']);

    Route::post('/program-remove', ['as' => 'program.remove', 'uses' => 'PartnerProgramsController@remove']);
    Route::resource('program.link', 'LinksController', ['except' => ['index']]);
    Route::get('program/{program_id}/link', ['as' => 'program.link.index', 'uses' => 'LinksController@list']);
    Route::post('/program-link-remove', ['as' => 'program.link.remove', 'uses' => 'LinksController@remove']);

    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);

    Route::post('/user-remove', ['as' => 'user.remove', 'uses' => 'UsersController@remove']);

    Route::get('/change-password', ['as' => 'user.password', 'uses' => 'UsersController@password']);

    Route::post('/user-change-password', ['as' => 'user.change.password', 'uses' => 'UsersController@changePassword']);

    Route::post('/meeting-remove', ['as' => 'meeting.remove', 'uses' => 'MeetingsController@remove']);
    Route::post('/qualification-remove', ['as' => 'qualification.remove', 'uses' => 'QualificationsController@remove']);
    Route::post('/package-remove', ['as' => 'package.remove', 'uses' => 'PackageNotificationsController@remove']);
});

app/app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\CourseCreateRequest;
use App\Http\Requests\CourseUpdateRequest;
use App\Repositories\CourseRepository;
use App\Validators\CourseValidator;
use App\Entities\Course;
use App\Entities\Tag;
use App\Entities\CourseTags;
use App\Entities\Package;
use App\Services\CourseService;

class CoursesController extends Controller
{
    protected $repository;
    protected $validator;
    protected $service;

    public function __construct(CourseRepository $repository, CourseValidator $validator, CourseService $service)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->service  = $service;
    }

    public function index()
    {
        if (request()->wantsJson()) {
            $user = request()->user();
            $courses = $this->service->getFromUser($user);
            foreach ($courses as  $item) {
                $item->image = $item->image_link;
            }
            return response()->json([
                'courses' => $courses,
                'status' => true,
            ]);
        } else {
            $courses = Course::orderBy('sequence')->where('type', 0)->get();
            return view('courses.index', ['courses' => $courses]);
        }
    }

    public function create()
    {
        $packages = Package::orderBy('id')->get()->pluck('name', 'id');
        return view('courses.create', ['packages' => $packages]);
    }

    public function store(Request $request)
    {
        $request = $this->service->store($request);

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages'],
        ]);

        return redirect()->route('course.index');
    }

    public function edit($id)
    {
        $course = Course::find($id);
        $packages = Package::orderBy('id')->get()->pluck('name', 'id');
        
        return view('courses.edit', ['course' => $course, 'packages' => $packages]);
    }

    public function show($id)
    {
        $course = Course::find($id);
        if (request()->wantsJson()) {
            $user = request()->user();

            $course->videos = $this->service->getVideosFromUser($user, $course);

            return response()->json([
                'data' => $course,
                'status' => true,
            ]);
        } else {
            $tags = Tag::orderBy('name')->get()->pluck('name', 'id');
            $tags_selected = $course->tags->pluck('id');

            return view('courses.edit', ['course' => $course, 'tags' => $tags, 'tags_selected' => $tags_selected]);
        }
    }

    public function update(Request $request, $id)
    {
        $request = $this->service->update($request, (int) $id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('course.index');
    }

    public function remove(Request $request)
    {
        $request = $this->service->delete($request->get('id'));

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('course.index');
    }

    public function sequence(Request $request){
        $request = $this->service->sequence($request->get('itens'));

        return response()->json($request);
    }
}

app/app/Http/Controllers/VideosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\VideoCreateRequest;
use App\Http\Requests\VideoUpdateRequest;
use App\Repositories\VideoRepository;
use App\Validators\VideoValidator;
use App\Entities\Video;
use App\Entities\Tag;
use App\Entities\Package;
use App\Services\VideoService;

class VideosController extends Controller
{
    protected $repository;
    protected $validator;
    protected $service;

    public function __construct(VideoRepository $repository, VideoValidator $validator, VideoService $service)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->service = $service;
    }

    public function list($course_id)
    {
        $videos = Video::orderBy('sequence')->where('course_id', $course_id)->get();

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $videos,
                'course_id' => $course_id,
                'status' => true,
            ]);
        } else {
            return view('courses.videos.index', ['videos' => $videos, 'course_id' => $course_id]);
        }
    }

    public function create($course_id)
    {
        $packages = Package::orderBy('id')->get()->pluck('name', 'id');
        $before_list = Video::orderBy('sequence')->where('course_id', $course_id)->get()->pluck('name', 'id');

        return view('courses.videos.create', ['course_id' => $course_id, 'packages' => $packages, 'before_list' => $before_list]);
    }

    public function store(Request $request, $course_id)
    {
        $request = $this->service->store($request, $course_id);

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages'],
        ]);

        return redirect()->route('course.video.index', ['id' => $course_id]);
    }

    public function edit($course_id, $id)
    {
        $video = Video::find($id);
        $packages = Package::orderBy('id')->get()->pluck('name', 'id');
        $before_list = Video::orderBy('sequence')->where('course_id', $course_id)->where('id', '<>', $id)->get()->pluck('name', 'id');

        return view('courses.videos.edit', ['video' => $video, 'packages' => $packages, 'course_id' => $course_id, 'before_list' => $before_list]);
    }

    public function update(Request $request, $course_id, $id)
    {
        $request = $this->service->update($request, (int) $course_id, (int) $id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('course.video.index', ['id' => $course_id]);
    }

    public function remove(Request $request)
    {
        $response = $this->service->delete($request->get('id'));

        session()->flash('success', [
            'success'   => $response['success'],
            'messages'  => $response['messages']
        ]);

        return redirect()->route('course.video.index', ['id' => $request->get('entity_id')]);
    }

    public function sequence(Request $request){
        $request = $this->service->sequence($request->all());

        return response()->json($request);
    }

    public function details(Request $request){        
        try {
            $request = $this->service->details($request->get('id'));

            return response()->json([
                'success' => $request['success'],
                'messages' => $request['messages'],
                'data' => $request['data'],
            ]);            
        } catch (\Exception $e) {
            return response()->json([
                'status' => false,
                'materials' => $e->getMessage(),
            ]);
        }
    }
}

app/resources/views/courses/videos/create.blade.php
@extends('templates.master')

@section('content-view')
<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Cadastrar Vídeo
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
                {!! Form::open(['route' => ['course.video.store', $course_id], 'method' => 'post', 'files' => true]) !!}
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="name">Name</label>
                            </div>
                            <div class="col-md-6">
                                <label for="name">Url para download</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-md-6">
                                {!! Form::text('url', null, ['class' => 'form-control', 'placeholder' => 'Url']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-md-6">
                                <label for="name">Embed do vídeo</label>
                            </div>
                            <div class="col-md-6">
                                <label for="name">Versão em áudio (Formato MP3)</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::textarea('embed', null, ['class' => 'form-control', 'placeholder' => 'Embed']) !!}
                            </div>
                            <div class="col-md-6">
                                {!! Form::file('audio', ['class' => 'form-control', 'id' => 'audio-upload', 'style'=>'display:none']) !!}
                                <audio controls class="preview-audio"></audio>
                                {!! Form::button('Selecionar', ['class' => 'btn btn-accent', 'id' => 'select-audio']) !!}  
                                {!! Form::button('Remover', ['class' => 'btn btn-danger', 'id' => 'remove-audio']) !!}  
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-6">
                                <label for="package_id">Liberar ao completar o vídeo</label>
                                {!! Form::select('package_id', $before_list, null, ['class' => 'form-control', 'placeholder' => 'Sem vídeo anterior']) !!}
                            </div>
                            <div class="col-6">
                                <label for="package_id">Restringir conteúdo ao pacote</label>
                                {!! Form::select('package_id', $packages, null, ['class' => 'form-control', 'placeholder' => 'Todos os pacotes']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-md-6">
                                <label for="name">Data e hora do envio de notificação</label>
                                {!! Form::datetimeLocal('publication', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-md-3 offset-md-9">
                                {!! Form::submit('Salvar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
    @include('templates.modal.upload-error')
@endsection

@section('js-view')
    @include('templates.js.upload-audio')
@endsection

app/resources/views/courses/videos/edit.blade.php
@extends('templates.master')
@section('content-view')

<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Editar Vídeo
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
                {!! Form::model($video, ['route' => ['course.video.update', $course_id, $video->id], 'method' => 'PUT', 'files' => true]) !!}
                <div class="form-row">
                    <div class="form-group col-12">
                        <div class="row">
                            <div class="col-6">
                                <label for="name">Nome</label>
                            </div>
                            <div class="col-6">
                                <label for="name">Url para download</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                {!! Form::text('name', $video->name, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-6">
                                {!! Form::text('url', $video->url, ['class' => 'form-control', 'placeholder' => 'Url']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-6">
                                <label for="name">Embed do vídeo</label>
                            </div>
                            <div class="col-6">
                                <label for="name">Versão em áudio (Formato MP3)</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                {!! Form::textarea('embed', $video->embed, ['class' => 'form-control', 'placeholder' => 'Embed']) !!}
                            </div>
                            <div class="col-6">
                                {!! Form::file('audio', ['class' => 'form-control', 'id' => 'audio-upload', 'style'=>'display:none']) !!}
                                
                                @if($video->audio)
                                    <audio controls class="preview-audio" style="display:block">
                                        <source src="{{ Storage::url($video->audio) }}" type="audio/mpeg">
                                    </audio>
                                @else
                                    <audio controls class="preview-audio"></audio>
                                @endif
                                {!! Form::button('Selecionar', ['class' => 'btn btn-accent', 'id' => 'select-audio']) !!}  
                                {!! Form::button('Remover', ['class' => 'btn btn-danger', 'id' => 'remove-audio']) !!}  
                                <input type="hidden" name="remove-audio" class="input-hidden" id="remove-hidden-audio" value="0">
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-6">
                                <label for="before_id">Liberar ao completar o vídeo</label>
                                {!! Form::select('before_id', $before_list, $video->before == null ? null : $video->before->id, ['class' => 'form-control', 'placeholder' => 'Sem vídeo anterior']) !!}
                            </div>
                            <div class="col-6">
                                <label for="package_id">Restringir conteúdo ao pacote</label>
                                {!! Form::select('package_id', $packages, $video->package == null ? null : $video->package->id, ['class' => 'form-control', 'placeholder' => 'Todos os pacotes']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-md-6">
                                <label for="name">Data e hora do envio de notificação</label>
                                {!! Form::datetimeLocal('publication', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-4 offset-8">
                                {!! Form::submit('Savar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
    @include('templates.modal.upload-error')
@endsection

@section('js-view')
    @include('templates.js.upload-audio')
@endsection

app/resources/views/courses/videos/index.blade.php
@extends('templates.master')
@section('content-view')

<!-- End Small Stats Blocks -->
<br>
@include('templates.alert')
<div class="row">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Lista de Vídeos
                    <a href="{{ route('course.video.create', $course_id) }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">add_circle</i> Adicionar
                        </button>
                    </a>
                    @if(request()->is('course/'.env('FIRST_STEPS').'/video*') === FALSE && request()->is('course/'.env('DAILY_VIDEOS').'/video*') === FALSE)
                        <a href="{{ route('course.index') }}" class="text-right">
                            <button type="button" class="btn btn-primary btn-sm btn-add btn-back">
                                <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                            </button>
                        </a> 
                    @endif
                </h6>
            </div>
            <div class="card-body p-0">
                <div class="card-body p-0 pb-3 text-center">
                    <table class="table table-course mb-0" id="sortFixed" data-course="{{$course_id}}">
                        <thead class="bg-light">
                            <tr>
                                <th scope="col" class="border-0">#</th>
                                <th scope="col" class="border-0">Miniatura</th>
                                <th scope="col" class="border-0">Nome</th>
                                <th scope="col" class="border-0">Pacote</th>
                                <th scope="col" class="border-0">Ações</th>
                                <th scope="col" class="border-0"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($videos as $key => $video)
                            <tr data-id="{{$video->id}}">
                                <td>{{$key + 1}}</td>
                                <td><img src="{{$video->thumbnail}}" class="thumb-list"/></td>
                                <td>{{$video->name}}</td>
                                <td>{{$video->package == null ? '-' : $video->package->name}}</td>
                                <td>
                                    <button type="button" class="btn btn-success btn-sm text-center" data-toggle="modal" data-target="#listModal" data-id="{{$video->id}}" data-name="{{$video->name}}">
                                        <i class="material-icons mr-1">play_arrow</i> Views
                                    </button>
                                    <a href="{{ route('course.video.edit', ['course_id' => $course_id, 'id' => $video->id]) }}">
                                        <button type="button" class="btn btn-primary btn-sm text-center">
                                            <i class="material-icons mr-1">edit</i>Editar
                                        </button>
                                    </a>
                                    <button type="button" class="btn btn-danger btn-sm text-center" data-toggle="modal" data-target="#deleteModal" data-id="{{$video->id}}" data-name="{{$video->name}}" data-entity="{{$course_id}}">
                                        <i class="material-icons mr-1">delete</i>Deletar
                                    </button>
                                </td>
                                <td><i class="material-icons drag-item">drag_handle</i></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
@include('templates.modal.delete', ['title' => 'Deseja excluir', 'route' => 'course.video.remove'])
@include('templates.modal.list', ['route' => 'course-video-details'])
@endsection

@section('js-view')
    @include('templates.js.sortable', ['url' => 'course-video-sequence'])
@endsection

@section('css-view')
    <link rel="stylesheet" href="https://code.jquery.com/ui/jquery-ui-git.css">
@endsection