app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'dashboard', 'uses' => 'Controller@index']);
Route::post('/login', ['as' => 'user.auth', 'uses' => 'Controller@auth']);
Route::get('/login', ['as' => 'user.login', 'uses' => 'Controller@login']);

Route::get('share/{username?}', ['as' => 'user.share', 'uses' => 'Controller@share']);

Route::middleware(['auth'])->group(function () {
    Route::resources([
        'tag' => 'TagsController',
        'tag-category' => 'TagCategoriesController',
        'course' => 'CoursesController',
        'webinar' => 'WebinarsController',
        'audio' => 'AudioController',
        'material-category' => 'MaterialCategoriesController',
        'material' => 'MaterialsController',
        'notification' => 'NotificationsController',
        'device' => 'DevicesController',
        'program' => 'PartnerProgramsController',
        'user' => 'UsersController',
        'meeting' => 'MeetingsController',
        'qualification' => 'QualificationsController',
        'package' => 'PackageNotificationsController',
    ]);

    Route::get('/logout', ['as' => 'user.logout', 'uses' => 'Controller@logout']);

    Route::post('/tag-remove', ['as' => 'tag.remove', 'uses' => 'TagsController@remove']);

    Route::post('/tag-category-remove', ['as' => 'tag-category.remove', 'uses' => 'TagCategoriesController@remove']);

    Route::post('/course-remove', ['as' => 'course.remove', 'uses' => 'CoursesController@remove']);
    Route::post('/course-sequence', ['as' => 'course.sequence', 'uses' => 'CoursesController@sequence']);
    Route::resource('course.video', 'VideosController', ['except' => ['index']]);
    Route::get('course/{course_id}/video', ['as' => 'course.video.index', 'uses' => 'VideosController@list']);
    Route::post('/course-video-remove', ['as' => 'course.video.remove', 'uses' => 'VideosController@remove']);
    Route::post('/course-video-sequence', ['as' => 'course.video.sequence', 'uses' => 'VideosController@sequence']);
    Route::post('/course-video-details', ['as' => 'course.video.details', 'uses' => 'VideosController@details']);

    Route::post('/webinar-remove', ['as' => 'webinar.remove', 'uses' => 'WebinarsController@remove']);

    Route::post('/audio-remove', ['as' => 'audio.remove', 'uses' => 'AudioController@remove']);
    Route::post('/audio-sequence', ['as' => 'audio.sequence', 'uses' => 'AudioController@sequence']);
    Route::post('/audio-details', ['as' => 'audio.details', 'uses' => 'AudioController@details']);

    Route::post('/material-category-remove', ['as' => 'material-category.remove', 'uses' => 'MaterialCategoriesController@remove']);
    Route::post('/material-remove', ['as' => 'material.remove', 'uses' => 'MaterialsController@remove']);
    Route::post('/material-sequence', ['as' => 'material.sequence', 'uses' => 'MaterialsController@sequence']);

    Route::post('/notification-remove', ['as' => 'notification.remove', 'uses' => 'NotificationsController@remove']);

    Route::post('/device-remove', ['as' => 'device.remove', 'uses' => 'DevicesController@remove']);

    Route::post('/program-remove', ['as' => 'program.remove', 'uses' => 'PartnerProgramsController@remove']);
    Route::resource('program.link', 'LinksController', ['except' => ['index']]);
    Route::get('program/{program_id}/link', ['as' => 'program.link.index', 'uses' => 'LinksController@list']);
    Route::post('/program-link-remove', ['as' => 'program.link.remove', 'uses' => 'LinksController@remove']);

    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);

    Route::post('/user-remove', ['as' => 'user.remove', 'uses' => 'UsersController@remove']);

    Route::get('/change-password', ['as' => 'user.password', 'uses' => 'UsersController@password']);

    Route::post('/user-change-password', ['as' => 'user.change.password', 'uses' => 'UsersController@changePassword']);

    Route::post('/meeting-remove', ['as' => 'meeting.remove', 'uses' => 'MeetingsController@remove']);
    Route::post('/qualification-remove', ['as' => 'qualification.remove', 'uses' => 'QualificationsController@remove']);
    Route::post('/package-remove', ['as' => 'package.remove', 'uses' => 'PackageNotificationsController@remove']);
});

app/app/Http/Controllers/LinksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\LinksCreateRequest;
use App\Http\Requests\LinksUpdateRequest;
use App\Repositories\LinksRepository;
use App\Validators\LinksValidator;
use App\Services\LinkService;
use App\Entities\PartnerProgram;

/**
 * Class LinksController.
 *
 * @package namespace App\Http\Controllers;
 */
class LinksController extends Controller
{
    protected $repository;
    protected $validator;
    protected $service;

    public function __construct(LinksRepository $repository, LinksValidator $validator, LinkService $service)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->service = $service;
        $this->middleware('auth');
    }

    public function list($program_id)
    {
        $links = PartnerProgram::find($program_id)->links;
        return view('programs.links.index', ['links' => $links, 'program_id' => $program_id]);
    }

    public function create($program_id)
    {
        return view('programs.links.create', ['program_id' => $program_id]);
    }

    public function store(Request $request, $program_id)
    {
        $request = $this->service->store($request, $program_id);

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages'],
        ]);

        return redirect()->route('program.link.index', ['id' => $program_id]);
    }

    public function edit($program_id, $id)
    {
        $link = $this->repository->find($id);

        return view('programs.links.edit', ['link' => $link, 'program_id' => $program_id]);
    }

    public function update(Request $request, $program_id, $id)
    {
        $request = $this->service->update($request, (int) $program_id, (int) $id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('program.link.index', ['id' => $program_id]);
    }

    public function remove(Request $request)
    {
        $response = $this->service->delete($request->get('id'));

        session()->flash('success', [
            'success'   => $response['success'],
            'messages'  => $response['messages']
        ]);

        return redirect()->route('program.link.index', ['id' => $request->get('entity_id')]);
    }    
}

app/resources/views/programs/links/create.blade.php
@extends('templates.master')
@section('content-view')

<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Criar Link
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
            {!! Form::open(['route' => ['program.link.store', $program_id], 'method' => 'post', 'files' => true]) !!}
                <div class="form-row">
                    <div class="form-group col-12">
                        <div class="row">
                            <div class="col-6">
                                {!! Form::label('name', 'Nome') !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-6">
                                {!! Form::label('code', 'Código') !!}
                                {!! Form::text('code', null, ['class' => 'form-control', 'placeholder' => 'Código']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-6">
                                <label for="name">Imagem</label>
                                {!! Form::file('image', ['class' => 'form-control', 'id' => 'image-upload', 'style'=>'display:none']) !!}
                                <img class="preview-image" />
                                {!! Form::button('Select', ['class' => 'btn btn-accent', 'id' => 'select-image']) !!}
                                {!! Form::button('Remove', ['class' => 'btn btn-danger', 'id' => 'remove-image']) !!}
                            </div>
                            <div class="col-6">
                                {!! Form::label('link', 'Link') !!}
                                {!! Form::text('link', null, ['class' => 'form-control', 'placeholder' => 'Link']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-4 offset-8">
                                {!! Form::submit('Salvar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
    @include('templates.modal.upload-error')
@endsection

@section('js-view')
    @include('templates.js.upload-image')
@endsection

app/resources/views/programs/links/edit.blade.php
@extends('templates.master')
@section('content-view')

<!-- Page Header -->
<div class="page-header row no-gutters py-4">
</div>
<!-- End Small Stats Blocks -->
<div class="row">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Editar Programa
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
                {!! Form::model($link, ['route' => ['program.link.update', $program_id, $link->id], 'method' => 'PUT', 'files' => true]) !!}
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="row">
                            <div class="col-6">
                                {!! Form::label('name', 'Nome') !!}
                                {!! Form::text('name', $link->name, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-6">
                                {!! Form::label('code', 'Código') !!}
                                {!! Form::text('code', $link->code, ['class' => 'form-control', 'placeholder' => 'Código']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-6">
                                <label for="name">Imagem</label>
                                {!! Form::file('image', ['class' => 'form-control', 'id' => 'image-upload', 'style'=>'display:none']) !!}
                                @if($link->image)
                                    <img src={{ Storage::url($link->image) }} class="preview-image"/>
                                @else
                                    <img class="preview-image"/>
                                @endif
                                {!! Form::button('Select', ['class' => 'btn btn-accent', 'id' => 'select-image']) !!}
                                {!! Form::button('Remove', ['class' => 'btn btn-danger', 'id' => 'remove-image']) !!}
                                <input type="hidden" name="remove-image" class="input-hidden" id="remove-hidden-image" value="0">
                            </div>
                            <div class="col-6">
                                {!! Form::label('link', 'Link') !!}
                                {!! Form::text('link', $link->link, ['class' => 'form-control', 'placeholder' => 'Link']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-4 offset-8">
                                {!! Form::submit('Salvar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
    @include('templates.modal.upload-error')
@endsection

@section('js-view')
    @include('templates.js.upload-image')
@endsection

app/resources/views/programs/links/index.blade.php
@extends('templates.master')
@section('content-view')

<!-- End Small Stats Blocks -->
<br>
@include('templates.alert')
<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Lista de Links
                    <a href="{{ route('program.link.create', $program_id) }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">add_circle</i> Adicionar
                        </button>
                    </a>
                    <a href="{{ route('program.index') }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add btn-back">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a> 
                </h6>
            </div>
            <div class="card-body p-0">
                <div class="card-body p-0 pb-3 text-center">
                    <table class="table table-company mb-0">
                        <thead class="bg-light">
                            <tr>
                                <th scope="col" class="border-0">#</th>
                                <th scope="col" class="border-0">Imagem</th>
                                <th scope="col" class="border-0">Nome</th>
                                <th scope="col" class="border-0">Código</th>
                                <th scope="col" class="border-0">Acões</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($links as $key => $link)
                            <tr>
                                <td>{{$key + 1}}</td>
                                <td>
                                    @if($link->image)
                                        <img src={{ Storage::url($link->image) }} class="py-2" style="max-width:150px">
                                    @endif
                                </td>
                                <td>{{ substr($link->name, 0 , 30) . '...' }}</td>
                                <td>{{ $link->code }}</td>
                                <td>
                                    <a href="{{ route('program.link.edit', ['program_id' => $program_id, 'id' => $link->id]) }}">
                                        <button type="button" class="btn btn-primary btn-sm text-center">
                                            <i class="material-icons mr-1">edit</i>Editar
                                        </button>
                                    </a>
                                    <button type="button" class="btn btn-danger btn-sm text-center" data-toggle="modal" data-target="#deleteModal" data-id="{{$link->id}}" data-name="{{$link->name}}" data-entity="{{$program_id}}">
                                        <i class="material-icons mr-1">delete</i>Deletar
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
@include('templates.modal.delete', ['title' => 'Deseja excluir', 'route' => 'program.link.remove'])
@endsection