app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'dashboard', 'uses' => 'Controller@index']);
Route::post('/login', ['as' => 'user.auth', 'uses' => 'Controller@auth']);
Route::get('/login', ['as' => 'user.login', 'uses' => 'Controller@login']);

Route::get('share/{username?}', ['as' => 'user.share', 'uses' => 'Controller@share']);

Route::middleware(['auth'])->group(function () {
    Route::resources([
        'tag' => 'TagsController',
        'tag-category' => 'TagCategoriesController',
        'course' => 'CoursesController',
        'webinar' => 'WebinarsController',
        'audio' => 'AudioController',
        'material-category' => 'MaterialCategoriesController',
        'material' => 'MaterialsController',
        'notification' => 'NotificationsController',
        'device' => 'DevicesController',
        'program' => 'PartnerProgramsController',
        'user' => 'UsersController',
        'meeting' => 'MeetingsController',
        'qualification' => 'QualificationsController',
        'package' => 'PackageNotificationsController',
    ]);

    Route::get('/logout', ['as' => 'user.logout', 'uses' => 'Controller@logout']);

    Route::post('/tag-remove', ['as' => 'tag.remove', 'uses' => 'TagsController@remove']);

    Route::post('/tag-category-remove', ['as' => 'tag-category.remove', 'uses' => 'TagCategoriesController@remove']);

    Route::post('/course-remove', ['as' => 'course.remove', 'uses' => 'CoursesController@remove']);
    Route::post('/course-sequence', ['as' => 'course.sequence', 'uses' => 'CoursesController@sequence']);
    Route::resource('course.video', 'VideosController', ['except' => ['index']]);
    Route::get('course/{course_id}/video', ['as' => 'course.video.index', 'uses' => 'VideosController@list']);
    Route::post('/course-video-remove', ['as' => 'course.video.remove', 'uses' => 'VideosController@remove']);
    Route::post('/course-video-sequence', ['as' => 'course.video.sequence', 'uses' => 'VideosController@sequence']);
    Route::post('/course-video-details', ['as' => 'course.video.details', 'uses' => 'VideosController@details']);

    Route::post('/webinar-remove', ['as' => 'webinar.remove', 'uses' => 'WebinarsController@remove']);

    Route::post('/audio-remove', ['as' => 'audio.remove', 'uses' => 'AudioController@remove']);
    Route::post('/audio-sequence', ['as' => 'audio.sequence', 'uses' => 'AudioController@sequence']);
    Route::post('/audio-details', ['as' => 'audio.details', 'uses' => 'AudioController@details']);

    Route::post('/material-category-remove', ['as' => 'material-category.remove', 'uses' => 'MaterialCategoriesController@remove']);
    Route::post('/material-remove', ['as' => 'material.remove', 'uses' => 'MaterialsController@remove']);
    Route::post('/material-sequence', ['as' => 'material.sequence', 'uses' => 'MaterialsController@sequence']);

    Route::post('/notification-remove', ['as' => 'notification.remove', 'uses' => 'NotificationsController@remove']);

    Route::post('/device-remove', ['as' => 'device.remove', 'uses' => 'DevicesController@remove']);

    Route::post('/program-remove', ['as' => 'program.remove', 'uses' => 'PartnerProgramsController@remove']);
    Route::resource('program.link', 'LinksController', ['except' => ['index']]);
    Route::get('program/{program_id}/link', ['as' => 'program.link.index', 'uses' => 'LinksController@list']);
    Route::post('/program-link-remove', ['as' => 'program.link.remove', 'uses' => 'LinksController@remove']);

    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);

    Route::post('/user-remove', ['as' => 'user.remove', 'uses' => 'UsersController@remove']);

    Route::get('/change-password', ['as' => 'user.password', 'uses' => 'UsersController@password']);

    Route::post('/user-change-password', ['as' => 'user.change.password', 'uses' => 'UsersController@changePassword']);

    Route::post('/meeting-remove', ['as' => 'meeting.remove', 'uses' => 'MeetingsController@remove']);
    Route::post('/qualification-remove', ['as' => 'qualification.remove', 'uses' => 'QualificationsController@remove']);
    Route::post('/package-remove', ['as' => 'package.remove', 'uses' => 'PackageNotificationsController@remove']);
});

app/app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\TagCreateRequest;
use App\Http\Requests\TagUpdateRequest;
use App\Validators\TagValidator;
use App\Repositories\TagRepository;
use App\Entities\Tag;
use App\Entities\TagCategory;
use App\Services\TagService;

class TagsController extends Controller
{

    protected $repository;
    protected $validator;
    protected $service;

    public function __construct(TagRepository $repository, TagValidator $validator, TagService $service)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->service = $service;
        $this->middleware('auth');
    }

    public function index()
    {
        return view('tags.index', ['tags' => Tag::orderBy('name')->get()]);
    }

    public function create()
    {
        $categories = TagCategory::orderBy('name')->get()->pluck('name', 'id');
        return view('tags.create', ['categories' => $categories]);
    }

    public function store(Request $request)
    {
        $request = $this->service->store($request->all());

        session()->flash('success', [
            'success' => $request['success'],
            'messages' => $request['messages'],
        ]);

        return redirect()->route('tag.index');
    }

    public function edit($id)
    {
        $tag = Tag::find($id);
        $categories = TagCategory::orderBy('name')->get()->pluck('name', 'id');

        return view('tags.edit', ['tag' => $tag, 'categories' => $categories]);
    }

    public function update(Request $request, $id)
    {
        $request = $this->service->update($request->all(), (int) $id);

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('tag.index');
    }

    public function remove(Request $request)
    {
        $request = $this->service->delete($request->get('id'));

        session()->flash('success', [
            'success'   => $request['success'],
            'messages'  => $request['messages']
        ]);

        return redirect()->route('tag.index');
    }
}

app/resources/views/tags/create.blade.php
@extends('templates.master')
@section('content-view')

<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Criar Tag
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
            {!! Form::open(['route' => 'tag.store', 'method' => 'post']) !!}
                <div class="form-row">
                    <div class="form-group col-12">
                        <div class="row">
                            <div class="col-6">
                                {{ Form::label('name', 'Nome') }}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-6">
                                {{ Form::label('category_id', 'Categoria') }}
                                {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-6">
                                {{ Form::label('description', 'Descricão') }}
                                {!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Descricão']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-md-4 offset-md-8">
                                {!! Form::submit('Salvar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>

@endsection

app/resources/views/tags/edit.blade.php
@extends('templates.master')
@section('content-view')

<!-- Page Header -->
<div class="page-header row no-gutters py-4">
</div>
<!-- End Small Stats Blocks -->
<div class="row">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Editar Tag
                    <a href="{{ redirect()->back()->getTargetUrl() }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">arrow_back_ios</i>Voltar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body flex-column">
                {!! Form::model($tag, ['route' => ['tag.update', $tag->id], 'method' => 'PUT']) !!}
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="row">
                            <div class="col-6">
                                {{ Form::label('name', 'Nome') }}
                                {!! Form::text('name', $tag->name, ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
                            </div>
                            <div class="col-6">
                                {{ Form::label('category_id', 'Categoria') }}
                                {!! Form::select('category_id', $categories, $tag->category->id, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col-6">
                                {{ Form::label('description', 'Descrição') }}
                                {!! Form::textarea('description', $tag->description, ['class' => 'form-control', 'placeholder' => 'Descrição']) !!}
                            </div>
                        </div>
                        <div class="row py-3">
                            <div class="col-md-4 offset-md-8">
                                {!! Form::submit('Salvar', ['class' => 'btn btn-accent btn-block']) !!}                  
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>

@endsection

app/resources/views/tags/index.blade.php
@extends('templates.master')
@section('content-view')

<!-- End Small Stats Blocks -->
<br>
@include('templates.alert')
<div class="row py-4">
    <!-- Top Referrals Component -->
    <div class="col-lg-12 col-md-12 col-sm-12 mb-12">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">
                    Lista de Tags
                    <a href="{{ route('tag.create') }}" class="text-right">
                        <button type="button" class="btn btn-primary btn-sm btn-add">
                            <i class="material-icons mr-1">add_circle</i> Adicionar
                        </button>
                    </a>
                </h6>
            </div>
            <div class="card-body p-0">
                <div class="card-body p-0 pb-3 text-center">
                    <table class="table table-company mb-0">
                        <thead class="bg-light">
                            <tr>
                                <th scope="col" class="border-0">#</th>
                                <th scope="col" class="border-0">Nome</th>
                                <th scope="col" class="border-0">Categoria</th>
                                <th scope="col" class="border-0">Acões</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($tags as $key => $tag)
                            <tr>
                                <td>{{$key + 1}}</td>
                                <td>{{$tag->name}}</td>
                                <td>{{$tag->category->name}}</td>
                                <td>
                                    <a href="{{ route('tag.edit', $tag->id) }}">
                                        <button type="button" class="btn btn-primary btn-sm text-center">
                                            <i class="material-icons mr-1">edit</i>Editar
                                        </button>
                                    </a>
                                    <button type="button" class="btn btn-danger btn-sm text-center" data-toggle="modal" data-target="#deleteModal" data-id="{{$tag->id}}" data-name="{{$tag->name}}">
                                        <i class="material-icons mr-1">delete</i>Deletar
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Referrals Component -->
</div>
@include('templates.modal.delete', ['title' => 'Deseja excluir', 'route' => 'tag.remove'])
@endsection